'use server';

/**
 * @fileOverview A comprehensive profit-sharing calculation system for platform revenue.
 *
 * - calculateProfitSharing - A function that calculates the distribution of platform revenue among various stakeholders.
 * - CalculateProfitSharingInput - The input type for the calculateProfitSharing function.
 * - CalculateProfitSharingOutput - The return type for the calculateProfitSharing function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const ProfitSharingConfigSchema = z.object({
    investor_share_percentage: z.number().min(0).max(100).describe('The percentage of revenue allocated to the investor pool.'),
    superadmin_share_percentage: z.number().min(0).max(100).describe('The percentage of revenue for the superadmin.'),
    admin_base_share_percentage: z.number().min(0).max(100).describe('The base percentage of revenue for the admin.'),
    staff_payroll_percentage: z.number().min(0).max(100).describe('The percentage of revenue allocated for staff salaries, to be managed by the admin.'),
    platform_reserve_percentage: z.number().min(0).max(100).describe('The percentage of revenue retained by the platform for operational costs and development.'),
}).refine(
    (data) => 
        Math.abs(
            data.investor_share_percentage +
            data.superadmin_share_percentage +
            data.admin_base_share_percentage +
            data.staff_payroll_percentage +
            data.platform_reserve_percentage - 100
        ) < 0.001,
    {
        message: "The sum of all percentages must be exactly 100.",
        path: ["investor_share_percentage", "superadmin_share_percentage", "admin_base_share_percentage", "staff_payroll_percentage", "platform_reserve_percentage"],
    }
);


export const CalculateProfitSharingInputSchema = z.object({
  total_platform_revenue: z.number().positive().describe('The total revenue generated by the platform for the period.'),
  config: ProfitSharingConfigSchema.describe('The configuration object for all profit-sharing percentages.'),
});
export type CalculateProfitSharingInput = z.infer<typeof CalculateProfitSharingInputSchema>;

export const CalculateProfitSharingOutputSchema = z.object({
  total_revenue: z.number().describe('The total platform revenue that was processed.'),
  distribution: z.object({
    investor_pool_amount: z.number().describe('The total amount distributed to the investor pool.'),
    superadmin_amount: z.number().describe('The amount distributed to the superadmin.'),
    admin_total_earning: z.number().describe('The total amount the admin receives (base share + staff payroll).'),
    platform_reserve_amount: z.number().describe('The amount retained by the platform.'),
  }),
  admin_earning_breakdown: z.object({
    admin_base_share: z.number().describe("The admin's personal share of the revenue."),
    staff_payroll_allocation: z.number().describe('The portion allocated for staff salaries, managed by the admin.'),
  }),
  parameters_used: ProfitSharingConfigSchema,
});
export type CalculateProfitSharingOutput = z.infer<typeof CalculateProfitSharingOutputSchema>;

/**
 * Calculates the automatic splitting of platform revenue among stakeholders.
 * @param input The total platform revenue and the configuration for splitting.
 * @returns A detailed breakdown of the amounts for each stakeholder.
 */
export async function calculateProfitSharing(
  input: CalculateProfitSharingInput
): Promise<CalculateProfitSharingOutput> {
  return calculateProfitSharingFlow(input);
}

const calculateProfitSharingFlow = ai.defineFlow(
  {
    name: 'calculateProfitSharingFlow',
    inputSchema: CalculateProfitSharingInputSchema,
    outputSchema: CalculateProfitSharingOutputSchema,
  },
  async (input) => {
    const { total_platform_revenue, config } = input;

    // Calculate amounts for each stakeholder based on percentages
    const investor_pool_amount = total_platform_revenue * (config.investor_share_percentage / 100);
    const superadmin_amount = total_platform_revenue * (config.superadmin_share_percentage / 100);
    const admin_base_share = total_platform_revenue * (config.admin_base_share_percentage / 100);
    const staff_payroll_allocation = total_platform_revenue * (config.staff_payroll_percentage / 100);
    const platform_reserve_amount = total_platform_revenue * (config.platform_reserve_percentage / 100);

    // Calculate the total amount the admin is responsible for
    const admin_total_earning = admin_base_share + staff_payroll_allocation;

    // Verify that the sum of splits equals the total revenue
    const sum_check = investor_pool_amount + superadmin_amount + admin_total_earning + platform_reserve_amount;
    if (Math.abs(sum_check - total_platform_revenue) > 0.001) {
        // This case should ideally not be hit if the Zod refine works correctly, but it's good practice.
        throw new Error(`Verification failed: Sum of splits (${sum_check}) does not equal total revenue (${total_platform_revenue}).`);
    }

    return {
      total_revenue: total_platform_revenue,
      distribution: {
        investor_pool_amount,
        superadmin_amount,
        admin_total_earning,
        platform_reserve_amount,
      },
      admin_earning_breakdown: {
        admin_base_share,
        staff_payroll_allocation,
      },
      parameters_used: config,
    };
  }
);
