name: Create Production Builds

on:
  push:
    branches:
      - main
    paths:
      - apps/mobile/**
      - packages/shared/**
      - package.json
      - package-lock.json

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: production

  build_ios:
    type: build
    params:
      platform: ios
      profile: production
